### ISSUE TITLE
move to Python 3.12

### ISSUE THREAD

**Issue by totaam** [Xpra-org/gtk-osx-build#32]
Blocked by: https://github.com/ronaldoussoren/py2app/issues/496

**Comment by totaam** [comment]
Trying to test in 215cdd3395684ae723247e1ba0ec8dbd4b73ce2b, but blocked by #44

**Comment by totaam** [comment]
I think we may need to update gi:
```
Traceback (most recent call last):
  File "/Users/macos12/.cache/jhbuild/build/gobject-introspection-1.80.1/tools/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/Users/macos12/.cache/jhbuild/build/gobject-introspection-1.80.1/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/Users/macos12/.cache/jhbuild/build/gobject-introspection-1.80.1/giscanner/ast.py", line 27, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/Users/macos12/.cache/jhbuild/build/gobject-introspection-1.80.1/giscanner/sourcescanner.py", line 25, in <module>
    from .ccompiler import CCompiler
  File "/Users/macos12/.cache/jhbuild/build/gobject-introspection-1.80.1/giscanner/ccompiler.py", line 29, in <module>
    from distutils.msvccompiler import MSVCCompiler
ModuleNotFoundError: No module named 'distutils.msvccompiler'
[89/174] Compiling C object tests/libgimarshallingtests-1.0.1.dylib.p/gimarshallingtests.c.o
ninja: build stopped: subcommand failed.
*** Error during phase build of gobject-introspection: ########## Error running ninja   *** [22/139]
```
For now, replacing the import with a fake one "fixes" this error, before erroring on #44.
